### ISSUE TITLE
Add a link to the used framework/library

### ISSUE THREAD

**Issue by mathieuboniface** [takimafr/androidkickstartr#1]
Actually AndroidKickstartR present each supported library/framework with a short sentence.

It would be nice to add a link to the associated documentation on each library/framework .
- http://androidannotations.org/
- http://actionbarsherlock.com/
- http://nineoldandroids.com/
- etc...

**Comment by ThomasFondrillon** [comment]
You can find each documentation by clicking on the `doc` button to the right of the library/framework summary.

There is also links which describe the usage of these libraries/frameworks.
