### ISSUE TITLE
.factorypath and pom.xml use different AA version

### ISSUE THREAD

**Issue by julienrenaut** [takimafr/androidkickstartr#102]
On a fresh maven repo AA-2.7.1 will be downloaded because of the pom.xml dependency but AA-2.7 in .factorypath won't leading to eclipse claiming:

 "Project test is missing required annotation processor library: 'M2_REPO/com/googlecode/androidannotations/androidannotations-api/2.7/androidannotations-api-2.7.jar'".

.factorypath should be updated to use the same version of AA in the pom.xml

**Comment by a-thomas** [comment]
Thanks, this issue has been fixed but not deployed yet.
Stay tuned.
