### ISSUE TITLE
Generated main activity 'EActivity' annotation to support AA 2.7+

### ISSUE THREAD

**Issue by full-of-foo** [takimafr/androidkickstartr#105]
Current generated main activity annotation is:

@EActivity(R.layout.activity_main)

As per the following, https://github.com/excilys/androidannotations/wiki/Library-projects ,it should be:

@EActivity(resName="activity_main")

**Comment by jeremiemartinez** [comment]
Well, actually in AA you can do both, either by name or by id. I prefer by id since it will better support refactoring. I also know for sure that resName has been introduced in AA for library project especially.

**Comment by full-of-foo** [comment]
@jeremiemartinez Hmmm strange, I am indeed seeing now that both are supported. When I initially generated my project (using the default Eclipse generation rather than Mvn or Gradle) I did the following:
- Imported both my app and actionbarsherlock through the generic project importer (not the Android project importer)
- Added actionbarsherlock as an Android library for the my app project
- Updated the '.facotrypath' file to be for the AA 2.7.1 jar rather than the 2.7 jar
- Cleaned and built all
- Error raised for "@EActivity(R.layout.activity_main)", which was that @EActivity does not expect a constant
- Changed it to "@EActivity(resName="activity_main")"
- Cleaned and built all
- Project compiled 

However, since your reply and after attempting to change the annotation back to "@EActivity(R.layout.activity_main)" it now simply works!?

**Comment by full-of-foo** [comment]
I'm sure this can be closed but it may be worth keeping around incase others encounter a similar issue? :smiley:

**Comment by jeremiemartinez** [comment]
Sure thing. @a-thomas ?

**Comment by a-thomas** [comment]
We will close this issue and re-open a new one if somebody else encounters this problem.
Thanks guys for the feedback

**Comment by full-of-foo** [comment]
:+1: Thanks guys
