### ISSUE TITLE
HTTP Status 400 - HTTP method POST is not supported by this URL

### ISSUE THREAD

**Issue by ntheile** [takimafr/androidkickstartr#107]
I'm trying to download the Full preset with eclipse and the sample code but get this error:

HTTP Status 400 - HTTP method POST is not supported by this URL

**Comment by MarcoABCorrea** [comment]
I'm having the same problem here...

**Comment by a-thomas** [comment]
It should be fixed ;)

**Comment by a-thomas** [comment]
Actually, it's not...

**Comment by ntheile** [comment]
It works now! Thanks
