### ISSUE TITLE
Get a 500 error when generating project

### ISSUE THREAD

**Issue by jwelch92** [takimafr/androidkickstartr#115]
Based on the other issues, it appears this project is abandoned.

**Comment by raviteja06** [comment]
java.lang.IllegalStateException: Couldn't create dir: generated/TestYouConfig-AndroidKickstartr/TestYouConfig/.settings
    com.athomas.androidkickstartr.util.FileHelper.createFile(FileHelper.java:121)
    com.athomas.androidkickstartr.util.FileHelper.getTargetEclipseJdtCorePrefsFile(FileHelper.java:167)
    com.athomas.androidkickstartr.Kickstartr.createDirectory(Kickstartr.java:161)
    com.athomas.androidkickstartr.Kickstartr.zipify(Kickstartr.java:67)
    com.athomas.androidkickstartr.Main.go(Main.java:177)
    sun.reflect.GeneratedMethodAccessor33.invoke(Unknown Source)
    sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    java.lang.reflect.Method.invoke(Method.java:606)
    com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$ResponseOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:187)
    com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:70)
    com.sun.jersey.server.impl.uri.rules.HttpMethodRule.accept(HttpMethodRule.java:279)
    com.sun.jersey.server.impl.uri.rules.ResourceClassRule.accept(ResourceClassRule.java:86)
    com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:136)
    com.sun.jersey.server.impl.uri.rules.RootResourceClassesRule.accept(RootResourceClassesRule.java:74)
    com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1357)
    com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1289)
    com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1239)
    com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1229)
    com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:420)
    com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:497)
    com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:684)
    javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
    org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
