### ISSUE TITLE
Custom Application class

### ISSUE THREAD

**Issue by aguynamedrich** [takimafr/androidkickstartr#14]
This is a good practice that a lot of newer Android developers may not know the value of.  Having the option to create a custom Application class and have it registered in the manifest would be a very valuable extra step in setting up.  This should have the option to select the name of the class as well as a sub-package of the main package.

**Comment by a-thomas** [comment]
In my opinion, the Application class should be added if it's needed. For example, we add id for a project with the ACRA dependency.
You're right, it's a good practice but we don't want to add some unused code.

Thanks for the suggestion.
