### ISSUE TITLE
Missing gen directory under the project

### ISSUE THREAD

**Issue by jeserkin** [takimafr/androidkickstartr#20]
I'm not sure whether it should be in project from the start or it can be created during build. If from the start, then you probably should add it.

**Comment by a-thomas** [comment]
Indeed, the gen folder isn't provided in the generated project. ADT should add it when you import the project into Eclipse. 

Could you tell me your Eclipse configuration ? (ADT ? Eclipse ?) And the libraries you chose ?

Thx

**Comment by jeserkin** [comment]
What do you mean by Eclipse configuration?
I've selected followin libraries:
- `AndroidAnnotations`
- `NineOldAndroids`
- `ACRA`
- `ActionBarSherlock ( Tab navigation )`
- `Android support v4`

**Comment by a-thomas** [comment]
I mean the version of Eclipse (Juno, indigo...) and the version of the Android Developer tools (ADT).

**Comment by jeserkin** [comment]
I'm using Eclipse Indigo 3.7.2 and ADT 20.0.3.v201208082019-427395

**Comment by a-thomas** [comment]
Thx @jeserkin.

The gen folder doesn't need to be into the generated project because it should be created by the ADT. 

So, if the gen project is missing, just follow this steps : [stackoverflow](http://stackoverflow.com/questions/5322901/import-existing-android-project-in-eclipse-no-gen-source-folder?answertab=votes#tab-top)

**Comment by jeserkin** [comment]
Okey. Sure, thanks. So to be clear. If everything works correctly then `gen` folder should be created automatically on project import or do I need to take those steps every time?

**Comment by a-thomas** [comment]
Exactly, the gen folder should be created by ADT at the importation into Eclipse.

But, I found something interesting. It seems this issue can be solved by setting the java version in project settings to 1.6.

Could you check the java version after the project import ?

**Comment by jeserkin** [comment]
Currently since project hasn't got any problems it add gen directory on Project Build. Java version vas set to 1.6 automatically.

**Comment by a-thomas** [comment]
Ok thanks. 

That's the same thing as #13.
