### ISSUE TITLE
@AfterViews isn't working for some reason

### ISSUE THREAD

**Issue by jeserkin** [takimafr/androidkickstartr#21]
Hello!

I've tried this project at home and it works as I expect after some tweaking, but when I tried same way at work I can't seem to get `@AfterViews` to work. Compiled project just starts on the emulator with style I specified in AndroidManifest.xml, but this is it. It doesn't even add hello message.

![App and project](http://dl.dropbox.com/u/4848045/app.png)

**Comment by a-thomas** [comment]
Hi @jeserkin, what kind of tweaking did you do ? :)

Did you modify the main activity name in the AndroidManifest by removing the `_` or referencing another activity ?

This `_` is needed when you're using AndroidAnnotations. That's well explained [here](https://github.com/excilys/androidannotations/wiki/HowItWorks).

**Comment by jeserkin** [comment]
That was probably the issue. Everyhting works fine now. Thank you.
