### ISSUE TITLE
Update the ABS version to 4.2.0

### ISSUE THREAD

**Issue by a-thomas** [takimafr/androidkickstartr#23]

**Comment by a-thomas** [comment]
Quote:

> Maven artifactId is now to 'actionbarsherlock'.

The `library` folder must be named `actionbarsherlock` instead. The documentation must be also updated.

**Comment by ThomasFondrillon** [comment]
Are you sure about the necessity to rename the `library` folder?

Maven artifactId has been effectively renamed to 'actionbarsherlock' but the ActionBarSherlock project still contains the `library` folder. If the `library` folder is renamed, the [documention about ActionBarSherlock usage](http://actionbarsherlock.com/usage.html) will not match.

**Comment by a-thomas** [comment]
There are two reasons for this choice:
- be able to add another library project such as the ViewPagerIndicator. The library folder name must not be the same.
- by default, "m2e for Android" use the `artifactId` of an `apklib` maven dependency to determine the path to the library which is added in the `project.properties` (default path= `../<artifactId>`) of the main project. Since the 4.2.0, the default path is `../actionbarsherlock`. Even if you force the path in the `project.properties`, it will be overwritten at the import.
