### ISSUE TITLE
The name of the project in eclipse

### ISSUE THREAD

**Issue by taharBakir** [takimafr/androidkickstartr#32]
When i create a project with a name of my choice, and import it in eclipse, the name showing in eclipse is not the name i specified but the fully qualified name of the main activity with an '_' at the end.

ex:
Application name: scary
Package name: com.scary
Main activity name: Shit

the name of the project in eclipse will be : "com.scary.Shit_"

that's weird.

Two solutions : I did something wrong or something's not right. :)

**Comment by a-thomas** [comment]
Hi @taharBakir, 

Did you import your project as a `General` project ? `Import > General > Existing projects into workspace`

Did you choose maven ? eclipse ?
