### ISSUE TITLE
404 instead of project download

### ISSUE THREAD

**Issue by ryabenko-pro** [takimafr/androidkickstartr#33]
When i press "Download"  button i got this (URL: http://ws.androidkickstartr.com/):

```
HTTP Status 400 - HTTP method POST is not supported by this URL

type Status report

message HTTP method POST is not supported by this URL

description The request sent by the client was syntactically incorrect (HTTP method POST is not supported by this URL).
```

After some tries I've got tarball, but with a lot of classes and with pretty class _ActionBarSherlockTrojanHorse 

```
package android.support.v4.app;
// ...

/** I'm in ur package. Stealing ur variables. */
public abstract class _ActionBarSherlockTrojanHorse extends FragmentActivity implements OnCreatePanelMenuListener, OnPreparePanelListener, OnMenuItemSelectedListener {
    private static final boolean DEBUG = false;
    private static final String TAG = "_ActionBarSherlockTrojanHorse";


```

Can't remember this class in prev tarball.

**Comment by a-thomas** [comment]
Hi @nord-ua, thanks a lot for posting this issue. 

Could you tell me the libraries you chose and all the parameters you chose to generate this project ? Moreover, could you send me the tarball (athomas.nc at gmail dot com) ?

Thanks a lot

**Comment by ryabenko-pro** [comment]
As I remember it was AndroidAnnotations, ACRA, ABS, Support v4

**Comment by a-thomas** [comment]
Thanks, I did some research about this class. In fact, `_ActionBarSherlockTrojanHorse` is an official class from ActionBarSherlock 4.1.0. Since the 4.2.0, this class has been renamed to [Watson](https://github.com/JakeWharton/ActionBarSherlock/blob/master/library/src/android/support/v4/app/Watson.java).

**Comment by a-thomas** [comment]
Jake Wharton said:

> It provides access to package-scoped things inside the support library which are not public.

**Comment by ryabenko-pro** [comment]
Good, thanx.
