### ISSUE TITLE
Proguard configs

### ISSUE THREAD

**Issue by jeremiemartinez** [takimafr/androidkickstartr#40]
I am currently using Proguard in almost all my projects and I thought it would be nice to have some Proguard configs possibly generated for Maven and No Maven projects.

If you think that something AndroidKickStartr should do, I could probably try to work on it. Let me know !

**Comment by ThomasFondrillon** [comment]
It's a very good idea. AndroidKickstartR offers a lot of libraries which can generate a big size project.

A good Proguard configuration for each library will assure the generation of a small size project !

**Comment by jeremiemartinez** [comment]
Thanks for your feedback. I will try to work on it asap since I have some free time currently. I will keep you posted about it !

**Comment by jeremiemartinez** [comment]
If everything is alright with this Pull Request we need to discuss how integrate it in AndroidKickStartr page, that is just radio buttons like Maven for instance. Let me know.

**Comment by a-thomas** [comment]
For the moment, I'll add a radio button and a link to the official documentation about proguard, but it should be great to add more documentation about the proguard config in the "Documentation" section on the website.

**Comment by jeremiemartinez** [comment]
Sure thing. I could probably try to come up with something!
