### ISSUE TITLE
error: Error retrieving parent for item

### ISSUE THREAD

**Issue by bkothari99** [takimafr/androidkickstartr#55]
Style.xml

error: Error retrieving parent for item: No resource found that matches the given name '@style/Theme.Sherlock.Light'

I got this error after importing ptoject.
Please give me some solution.

Thanks.

**Comment by a-thomas** [comment]
Hi @bkothari99, 

If you have generated a project containing ActionBarSherlock, the `actionbarsherlock` folder must be imported in Eclipse first. `@style/Theme.Sherlock.Light` is a reference to an ABS style. 

Could you give me more information about the project you have generated ?

**Comment by bkothari99** [comment]
Can you Please tell me How can I use android:theme="@style/Theme.Sherlock.ForceOverflow" in this project.
when I use it then It show me error.

**Comment by a-thomas** [comment]
This problem seems related to ActionBarSherlock. Please visit the [github](https://github.com/JakeWharton/ActionBarSherlock/issues) or the official documentation.
