### ISSUE TITLE
Option to Disable Sample Code Generation

### ISSUE THREAD

**Issue by commonsguy** [takimafr/androidkickstartr#58]
The approach that AndroidKickstartR (and the Eclipse ADT activity wizard templates) take of code-generating a complete working sample is cool... the first time that you use the templates.

However, the odds of a developer actually _using_ any of that code is relatively low. Few apps will be loading a string-array resource and using that to populate the titles of a set of action bar tabs, for example. It's not that the code is wrong, but that it is unrelated to the actual objective of the developer, forcing the developer to track down all of this stuff and get rid of it. Admittedly, Lint is getting better about reporting unused resources, which helps clear this out.

That being said, having an option to get rid of the sample code, generating just a bare activity with the minimal set of required initialization, would be useful for those using AndroidKickstartR for the second and subsequent times, so they do not have to track down and rip out all the stuff they didn't need (or even really specifically ask for). This will help AndroidKickstartR be more useful for seasoned developers, in addition to newcomers to Android.

Just a thought...

**Comment by a-thomas** [comment]
Hi @commonsguy, thanks for your feedback.
You are definitely right. I'm gonna add this issue in the roadmap right now.

**Comment by a-thomas** [comment]
I will close this issue when I will deploy the core+ws and update the website.

**Comment by a-thomas** [comment]
Merged on dev-pages branch waiting for the next deployment.
