### ISSUE TITLE
Scroll to input field which has invalid data entered

### ISSUE THREAD

**Issue by methical** [takimafr/androidkickstartr#61]
I had entered invalid characters for the project name and scrolled down to download the project but nothing happened. First I thought something was broke because there was no error prompt. I accidently scrolled to the top to find out that there were some tiny error messages.

Happened on Chrome (latest version) with AdBlock disabled and a resolution of 1680x1050.

Proposal: Either make a dialog box which states that there are errors (and thus making the user think to check his inputs again) or add an automatic scroll to the input field which has incorrect data entered upon clicking on the download button.

**Comment by jeremiemartinez** [comment]
+1, It happened to me last week !

**Comment by a-thomas** [comment]
Thanks a lot for this issue and for the suggestions. The window will be scrolled to the top if fields are wrong.
