### ISSUE TITLE
"Multiple dex files define.." error when using Eclipse+Maven-ABS

### ISSUE THREAD

**Issue by martyglaubitz** [takimafr/androidkickstartr#68]
The Eclipse Maven compiler plugin does not understand the scope "test", thus it will add org.hamcrest, which is included in org.junit, twice to the buildpath.

to fix this, add the exclusion as shown in the picture 
![excludehamcrest](https://f.cloud.github.com/assets/1542037/391958/ad6cbfaa-a772-11e2-8578-03310d7f9c0c.png)
to the pom.xml of the actionbarsherlock project

(i submit this as issue because i dont want to mess around in the project code)

**Comment by a-thomas** [comment]
Thanks for this suggestion but AndroidKickstartR doesn't have to modify the libraries it uses.
This fix should be part of the ABS project directly but, I don't think that Jake Wharton want to modify something that depends on the IDE.

Have you tried to exclude the `hamcrest-core` dependency directly from the abs dependency in your project pom ?

**Comment by martyglaubitz** [comment]
thanks, that did it to :)

**Comment by a-thomas** [comment]
Cool ;)

**Comment by martyglaubitz** [comment]
wait. we celebrated to early - i didn't work in a similar configured project.
again i had to set the exclusion on the junit dependency... 
_sigh_ ADT drives me crazy...
anyways - that's not your projects fault so i think i keep this issue closed
