### ISSUE TITLE
Add Roboguice support

### ISSUE THREAD

**Issue by jeromevdl** [takimafr/androidkickstartr#8]
To replace Android Annotations, provide Roboguice : http://code.google.com/p/roboguice/

**Comment by a-thomas** [comment]
Thanks you for this issue. 

But it seems that the word "replace" is not really relevant. I don't want to **replace** AndroidAnnotations but **add** Roboguice. Roboguice is a really awesome lib. AndroidAnnotations too ;)

**Comment by jeromevdl** [comment]
Yes, that's what i wanted to say. It's an alternative to AndroidAnnotations ;)

**Comment by ThomasFondrillon** [comment]
I'm working on this issue and I encountered a problem : both RoboGuice and ActionBarSherlock require custom base classes for Activities and Fragments.

The solution is to use custom RoboGuice classes that extend the corresponding ones from ActionBarSherlock.
@JakeWharton provided the first example of how to do this with a [RoboSherlockActivity](https://github.com/JakeWharton/ActionBarSherlock/blob/4.0.0/samples/roboguice/src/com/actionbarsherlock/sample/roboguice/RoboSherlockActivity.java) and @rtyley created [roboguice-sherlock](https://github.com/rtyley/roboguice-sherlock) which provides customs Activities and Fragments supporting RoboGuice and ActionBarSherlock.

So I think it's a good idea to include all required RoboSherlock classes if the user choose to generate a project with RoboGuice and ActionBarSherlock.

I am open to any other solution :)

**Comment by a-thomas** [comment]
The documentation must be udpated before considering this issue closed.

**Comment by a-thomas** [comment]
Done
