### ISSUE TITLE
Webpage doesn't scroll all the way to the top when title/activty/path is wrong

### ISSUE THREAD

**Issue by johanforssell** [takimafr/androidkickstartr#80]
Using Safari 6.0.4.

Tried to create an app with a space in the name.
The webpage didn't scroll all the way to the top when I pressed the download button, leaving me to wonder what went wrong. I could not see the error messages until I manually scrolled the webpage to the top.

**Comment by a-thomas** [comment]
Hi @johanforssell ,

Thanks for your feedback. This issue has been already fixed. See #61. 
We'll deploy a new version really soon.

Stay tuned.
