### ISSUE TITLE
AndroidAnnotations + Roboguice

### ISSUE THREAD

**Issue by arturgaleno** [takimafr/androidkickstartr#86]
Hello!

We already can use those two frameworks together :)

I saw in the following example: https://code.google.com/p/androidannotations/wiki/RoboGuiceIntegration

Maybe you could add this feature to AndroidKickStartr.

Regards

**Comment by a-thomas** [comment]
Hi @arturgaleno, 

Currently we support Roboguice 2.0. The 2.0 is not compatible with AndroidAnnotations. An [issue](https://github.com/excilys/androidannotations/issues/172) is still opened.
