### ISSUE TITLE
Unable to load annotation processor factory '/AndroidKickStartTest/ext-libs/androidannotations-2.6.jar'

### ISSUE THREAD

**Issue by pcrane** [takimafr/androidkickstartr#9]
If anyone else gets this message it's because it can't find the android annotations jar file. 

You can fix this by going to **Project Properties**, selecting **Java Compiler** and expanding the **Annotation Processing** item. You can then remove and re-add the appropriate jar file under the **Factory Path**.

Once I did this, then the project built without any problems.

**Comment by a-thomas** [comment]
Thank you. I fixed (9a6991bd75e0c72da3f240dc5de1d02dc07de595) the bug and redeployed. Could you try again and tell me if it works?

**Comment by pcrane** [comment]
Still getting the same issue when downloading the zip file from http://androidkickstartr.com/. It looks like you've got `<application_name>` instead of `<package_name>.<MainActivityName>_` for that field.

This setting sits in a `.factorypath` file in the same place as `.project`, `.settings/` and so on. The contents of the .factorypath file is below:

```
<factorypath>
    <factorypathentry kind="WKSPJAR" id="/LazyRestTest/ext-libs/androidannotations-2.6.jar" enabled="false" runInBatchMode="false"/>
    <factorypathentry kind="WKSPJAR" id="/net.pcrane.android.MainActivity_/ext-libs/androidannotations-2.6.jar" enabled="true" runInBatchMode="false"/>
</factorypath>
```

**Comment by a-thomas** [comment]
Hi pcrane, 

Have you followed the two steps:

1) For ABS : **Create** an "Android project from existing Code" and set the path to the library dir.
2) For your app: **Import** the your project as a **General** project in Eclipse (_Import_ > _General_ > _Existings project into workspace_) and not as an "Existing Android Code into workspace". Importing your project as an "Existing Android Code into workspace" results to the error that you mention above.

Could you tell me the librairies you chose and the parameters (maven? eclise?) of your application. I need these informations for helping you.

Regards

**Comment by a-thomas** [comment]
I consider this issue is solved.

**Comment by mircobabini** [comment]
I'm having a similar issue. I downloaded the zip with maven integration, imported actionbarsherlock and the main project too. All done, but i'm having the issue with androidannotations, even if it's a satisfied maven dependency.

Going through i noticed it's looking for AA 2.7 even if in the pom it's set to look for AA 2.7.1.
Of course i can just change the sources but.. why?

Regards

**Comment by graham-huck** [comment]
> Going through i noticed it's looking for AA 2.7 even if in the pom it's set to look for AA 2.7.1.
> Of course i can just change the sources but.. why?

I can also confirm that the current version of androidkickstartr references the wrong version of AndroidAnnotations.  Updating the Factory Path references in the project properties fixes the issue.

**Comment by Fabii23** [comment]
Thank you kindly. Fixed it.

**Comment by androidvsourz** [comment]
@pcrane -- You are simply awesome
 You saved my day
