### ISSUE TITLE
project shows errors after import in eclipse

### ISSUE THREAD

**Issue by syamantak** [takimafr/androidkickstartr#96]
Its a androidannotations-2.7.1 and androidannotations-2.7 library issue.
Somethings not updated while moving to 2.7.1
Please fix it and its a good tool

**Comment by a-thomas** [comment]
Hi. In fact the factory path has not been updated. I'll do it. Thanks for the feedback.

**Comment by a-thomas** [comment]
See f4d756951c8411c87292a33fef3333465a588374
