### ISSUE TITLE
Empty folder in generated zip archive

### ISSUE THREAD

**Issue by kyberorg** [takimafr/androidkickstartr#97]
Steps to reproduce:

1) Adjust application at website
2) Click download it
3) Open downloaded zip with standart windows tool
![void-win](https://f.cloud.github.com/assets/4687253/907409/c4f1509e-fd37-11e2-833d-3dff938855aa.PNG)
4) Try to unzip
![void-unzip](https://f.cloud.github.com/assets/4687253/907410/eb9a4cfa-fd37-11e2-8f7e-c34abbc45904.PNG)
Error text is: Cannot complete extracting. Compressed ZIP folder "C:\path\to\file.zip" has wrong format

or
3) go to place where zip-archive was downloaded
4) open archive with 7zip
5) see single folder with empty name
![void](https://f.cloud.github.com/assets/4687253/907412/2b691154-fd38-11e2-96c0-6551c496bd86.PNG)
6) When open this folder it looks like this
![void-inside](https://f.cloud.github.com/assets/4687253/907417/738baabe-fd38-11e2-9fba-0d2cf17ef027.PNG)

My OS - Windows 7 Ultimate (Russian), arch x86_64

**Comment by a-thomas** [comment]
Really weird.

Could you tell us the parameters and libraries you chose ? Thx.

**Comment by kyberorg** [comment]
Sure. 
1. Parameters

ApplicationName - GUITest
PackageName - net.virtalab.android.guitest
Main activity name: StartActivity

Eclipse as IDE: off
Proguard config: off
Sample code: on
1. Maven
   Android-Maven-Plugin: on
2. Choose your libraries
   AndroidAnnotations
   ACRA
   ActionBarSherlock (Tab Navigation)
   Android support v4
   ViewPager sample (New)

Also I just now tested same configuration at Windows 7 Ultimate (English) at my work. 
Same empty folder

**Comment by a-thomas** [comment]
Really really weird. I tried this combination (libraries+parameters) and even more. I always get a well archive file containing the generated project.
Could you try to do it again and send me the zip file by email ? (athomas.nc at gmail dot com)

Thx

**Comment by kyberorg** [comment]
Just sent e-mail with archive to you

**Comment by a-thomas** [comment]
The archive file contained the generated project. It's maybe due to the extractor tool or maybe related to an encoding problem. In any case, it's a user side problem.
I'll close this issue. We will open it again if the problem can be solved from the server side.

**Comment by dwursteisen** [comment]
Got the same issue

checked : 
- sample code
- android-maven
- android-annotation

OS : windows 7 X64bit + Chrome

is this [line from Zipper.java](https://github.com/a-thomas/androidkickstartr/blob/master/androidkickstartr-core/src/main/java/com/athomas/androidkickstartr/util/Zipper.java#L46) can be a problem if the path is only "generated" ?

**Comment by dwursteisen** [comment]
I "may" have fund the problem.

On ubuntu : unzip -l whatever-AndroidKickstarter.zip give : 

```
  Length      Date    Time    Name
---------  ---------- -----   ----
      611  2013-09-03 18:19   /Whatever-AndroidKickstartr/Quotes/src/main/java/com/github/dwursteisen/whatever/HomeActivity.java
[...]
```

another zip file (bootstrap-3.0.0.zip here) give this : 

```
  Length      Date    Time    Name
---------  ---------- -----   ----
        0  2013-08-19 22:49   dist/
[...]
```

notice the `/` containing in the path from the zip from AndroidKickstarter.
Unbuntu deal this without any problem, but default zip manager from Windows doesn't like it.

Regards
