### ISSUE TITLE
Send POST data with rest

### ISSUE THREAD

**Issue by bperin** [takimafr/androidkickstartr#99]
Is it possible to send post data as key value pairs along with a POST request? I can't seem to figure it out.

So I could do something like 

```
@Rest(rootUrl = "http://domain.com/", converters = StringHttpMessageConverter.class)
public interface RestClient {

@Post("/login")
Session forceLogin(String email,String Password);
}
```

**Comment by a-thomas** [comment]
Your question is more related to https://github.com/excilys/androidannotations . 
Feel free to ask questions on the google group or if it's an error on the github issues.
